permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# 作者信息
author: 
  name: GitDC
  email: dchan0831@gmail.com
  link: http://www.gitdc.com
  weibo: http://weibo.com/207124240
  github: http://github.com/gitcdc

# 站点信息
title: GitDC | 探索互联网之路
description: GitDC | 探索互联网之路
url: http://www.gitdc.com
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://blog.gitdc.com/wp-content/uploads/avatars/1/1423400103-bpfull.jpg
favicon: http://blog.gitdc.com/favicon.ico

# google analytics 设置
ga:
  id: UA-73362052-1
  url: gitdc.com

# disqus 设置
disqus:
  shortname: gitdc
